### ISSUE TITLE
turn this into a GH hosted page

### ISSUE THREAD

**Issue by royemosby** [mmeurer00/mergeMe#6]
It would be nice if this repo used GH pages or some other way to view the HTML. I've done that with my own fork to demo: https://royemosby.github.io/mergeMe/index.html

**Comment by mmeurer00** [comment]
I fully agree with you Roy, I spoke with Nicoll about this a day or so ago and it is in the making! Thank you for including that as well!

**Comment by mmeurer00** [comment]
Complete!
